<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>ArixcelExplorer.Core</RootNamespace>
    <AssemblyName>ArixcelExplorer.Core</AssemblyName>
    <SignManifests>false</SignManifests>
    <MSBuildEnableWorkloadResolver>false</MSBuildEnableWorkloadResolver>
  </PropertyGroup>
</Project>
